export PATH := ../../venv/bin:$(PATH)

.PHONY: print
print:
	./print.sh &> print.console

.PHONY: indentation
indentation:
	./indentation.sh &> indentation.console

.PHONY: all
all: print indentation
