export PATH := ../../venv/bin:$(PATH)

.PHONY: print-formatted-strings
print-formatted-strings:
	./print_formatted_strings.sh &> print_formatted_strings.console

.PHONY: all
all: print-formatted-strings
