.PHONY: pyenv
pyenv:
	./pyenv.sh &> pyenv.console

.PHONY: virtualenv
virtualenv:
	# Notice: the output is likely to change
	# ./virtualenv.sh &> virtualenv.console

.PHONY: all
all: pyenv virtualenv
