.PHONY: pyenv
pyenv:
	./pyenv.sh &> pyenv.console

.PHONY: virtualenv
virtualenv:
	# ./virtualenv.sh &> virtualenv.console
	# avoid output changes each time, mark it?
	# Output is likely to change

.PHONY: all
all: pyenv virtualenv
